import { auth } from "@/src/app/auth";
import LayoutStyleOne from "@/src/components/layouts/LayoutStyleOne";
import { redirect } from "next/navigation";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

const AboutView = async () => {
  const session = await auth();
  if (!session) redirect("/login");
  return (
    <LayoutStyleOne>
      <main>
        <h3 className="text-xl text-heading text-center mt-5">
          This is about page
        </h3>
      </main>
    </LayoutStyleOne>
  );
};

export default AboutView;
