import LoginForm from "@/src/components/form/LoginForm";
import LayoutStyleOne from "@/src/components/layouts/LayoutStyleOne";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const PrivacyPolicyView = () => {
  return (
    <LayoutStyleOne>
      <main>
        <div className="py-15">
          <div className="container">
            <LoginForm />
          </div>
        </div>
      </main>
    </LayoutStyleOne>
  );
};

export default PrivacyPolicyView;
