import LayoutStyleOne from "@/src/components/layouts/LayoutStyleOne";
import apiClient from "@/src/utils/apiClient";

export const metadata = {
  title: "All Posts",
  description: "Generated by create next app",
};

const BlogView = async () => {
  const data = await apiClient("/users/profile/posts");

  return (
    <LayoutStyleOne>
      <main>
        <h3 className="text-xl text-heading text-center mt-5">
          This is blog page
        </h3>
        <pre>data: {JSON.stringify(data, null, 2)}</pre>
      </main>
    </LayoutStyleOne>
  );
};

export default BlogView;
